### ISSUE TITLE
Display transations in original channel and in participants DMs

### ISSUE THREAD

**Issue by dyc3** [dyc3/discord-pokemon-battles#46]
Transactions describe what exactly happened in the battle.

Transaction fields:
- `type` - int - Denotes the type of transaction
- `name` - str - The name of the transaction
- `args` - dict - The transaction's parameters. Different transactions can have different parameters

**Comment by elenirotsides** [comment]
NOTE TO SELF: in simulate function (coordinator.py) `self.transactions += results.transactions` display results.transactions in an embed or whatever works
