### ISSUE TITLE
Load pokemon from database by ID

### ISSUE THREAD

**Issue by dyc3** [dyc3/discord-pokemon-battles#69]
We can save pokemon to the database, but we can't load them back up without directly interacting with `storage.db`

- Should take `ObjectId`
- Should return `Pokemon`
- Should raise exception if not found

**Comment by elenirotsides** [comment]
@dyc3 Do you plan on taking this? I like working with mongo so I think this is something I can confidently do.

**Comment by dyc3** [comment]
go for it
