### ISSUE TITLE
Need a command to quickly set up a random battle

### ISSUE THREAD

**Issue by dyc3** [dyc3/discord-pokemon-battles#8]
For testing purposes, it would be nice to have a command that would set up a random battle between 2 parties.

Currently, the challenge command does make a random battle, but it only generates 1v1 battles.

A random battle has 2 parties with a random amount (1-6) of random pokemon in each party, where each pokemon has random moves.

**Comment by elenirotsides** [comment]
Can you further define 'random battle' when you get a chance? Does this mean that a user will be able to challenge any random user that's online in the server? @dyc3

**Comment by dyc3** [comment]
Updated original issue.
